sudo: required

language: go

services:
  - docker

env:
  - DOCKER_BIND_LOCALHOST=true

go:
  - 1.5

before_install:
  - docker pull postgres

install:
  - go get golang.org/x/tools/cmd/vet
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go install github.com/golang/lint/golint
  - go get -t ./...

script:
  - go vet -x *.go
  - go lint ./
  - ./coverage --coveralls
