sudo: required

language: go

services:
  - docker

env:
  - DOCKER_BIND_LOCALHOST=true

go:
  - 1.4
  - 1.5
  - 1.6
  - tip

matrix:
  allow_failures:
    - go: tip
    - go: 1.4

install:
  - go get github.com/mattn/goveralls golang.org/x/tools/cmd/cover github.com/pierrre/gotestcover
  - glide install

script:
  - go vet -x .
  - gotestcover -coverprofile="cover.out" -race -covermode="count" .
  - goveralls -coverprofile="cover.out"
